### PR TITLE
Wrong index used for month_table array

### PR DESCRIPTION
**Pull request by m-seker**
Fixed array access according to 0 based indexing

### CODE REVIEW

**Comment by toelke** [comment]
According to <https://linux.die.net/man/3/gmtime>, the month-field of `struct tm` ranges from 0 to 11.

**Comment by m-seker** [comment]
I didn't know that, thanks !

**Comment by toelke** [comment]
Now that I think about it, this might also be intresting in https://github.com/toelke/lwip-ftpd/commit/d8830c3540ea251e3c660a684df947a83fcf9c38 :-)

**Comment by m-seker** [comment]
It'll show 1 Feb 1970 :)

**Pull request closed without merging**
